### 목록 (일반 유저)
GET http://localhost:8080/api/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbGljZSIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzU5MTI4MzMzLCJleHAiOjE3NTkxNjQzMzN9.K1-mIBQi1XrQmn4L176MVwHBKYROrfnvUVK9zc-ykyQ

### 회원가입
POST http://localhost:8080/api/auth/signup
Content-Type: application/json

{ "username": "alice", "password": "pw1234" }

### 로그인 -> 토큰 받기
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{ "username": "alice", "password": "pw1234" }

### 보호 API 호출 (토큰 사용)
GET http://localhost:8080/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbGljZSIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzU5MTA3NTE5LCJleHAiOjE3NTkxNDM1MTl9.UAzqhWodZ3yw6GCXzw1UKkN8EzWf_MjAcyNbhrnypq8

### fastAPI 감정 분석 테스트
Content-Type: multipart/form-data; boundary=BOUNDARY

--BOUNDARY
Content-Disposition: form-data; name="file"; filename="sample.m4a"
Content-Type: application/octet-stream

< C:\Users\user\Downloads\sample.m4a
--BOUNDARY--

### 업로드 (토큰 필요)
POST http://localhost:8080/api/recordings
Content-Type: multipart/form-data; boundary=boundary
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbGljZSIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzU5MTQyODY1LCJleHAiOjE3NTkxNzg4NjV9.6BZF7UxNFvVxGvwlKRTjLiWCaW21aCiW0LS4iE3HoRI

--boundary
Content-Disposition: form-data; name="file"; filename="test_1.m4a"
Content-Type: audio/m4a

< C:\Users\user\Downloads\test_1.m4a
--boundary
Content-Disposition: form-data; name="description"

오늘은 날씨가 좋아서 기분이 좋음
--boundary
Content-Disposition: form-data; name="latitude"

35.1796
--boundary
Content-Disposition: form-data; name="longitude"

129.0756
--boundary
Content-Disposition: form-data; name="address"

부산광역시 중구 중앙대로
--boundary
Content-Disposition: form-data; name="emotion"

true
--boundary--

### 특정 녹음 파일 다운로드/스트리밍
GET http://localhost:8080/api/recordings/6/file